# Generated by Django 4.2 on 2023-09-01 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=256)),
                ("schedule", models.CharField(max_length=35)),
                ("deadline", models.DateField()),
                ("contact", models.CharField()),
                ("contact_url", models.TextField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("is_private", models.BooleanField()),
            ],
            options={
                "db_table": "posts",
                "db_table_comment": "작성글 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
