# Generated by Django 4.2 on 2023-09-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_activate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
    ]
