# Generated by Django 4.2 on 2023-12-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_is_activate_post_score_alter_post_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
