# Generated by Django 4.2 on 2023-09-01 13:25

from django.db import migrations, models
import skills.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="skill"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        storage=skills.models.OverwriteStorage(),
                        upload_to=skills.models.Skill.skill_image_path,
                        verbose_name="skill image",
                    ),
                ),
            ],
        ),
    ]
