# Generated by Django 4.2 on 2023-12-11 12:16

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_userimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profile_images/basic/profile_image1.webp",
                upload_to=user.models.UserImage.user_image_path,
                verbose_name="profile image",
            ),
        ),
    ]
